async function maintain() {}

async function remind(loanId) {}

async function guildsWithin() {
  return [
    {
      id: "guild1",
      name: "Guild One",
      icon: null,
      banner: null,
      owner: false,
      permissions: 0,
      permissions_new: "0",
      features: [],
      members: [
        {
          id: "123456789",
          username: "dummyuser",
          displayname: "Dummy User",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "987654321",
          username: "otheruser",
          displayname: "Other User",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "135263456435",
          username: "13",
          displayname: "Other 13",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "87964236",
          username: "12",
          displayname: "Other 12",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "2346475678",
          username: "11",
          displayname: "Other 11",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "234654689",
          username: "10",
          displayname: "Other 10",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "1235437586",
          username: "9",
          displayname: "Other 9",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "982437698076",
          username: "8",
          displayname: "Other 8",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "234368978083",
          username: "7",
          displayname: "Other 7",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "123523465685654",
          username: "6",
          displayname: "Other 6",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "235975764",
          username: "5",
          displayname: "5",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "1875239698",
          username: "4",
          displayname: "4",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "243623489569746",
          username: "3",
          displayname: "3",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "2346135123",
          username: "2",
          displayname: "Other 2",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "212131235123",
          username: "1",
          displayname: "1",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
        {
          id: "1122143246234",
          username: "1",
          displayname: "2",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
      ],
    },
    {
      id: "guild2",
      name: "Guild Two",
      icon: null,
      banner: null,
      owner: false,
      permissions: 0,
      permissions_new: "0",
      features: [],
      members: [
        {
          id: "123456789",
          username: "dummyuser",
          displayname: "Dummy User",
          discriminator: "0000",
          avatar: null,
          bot: false,
          roles: [],
        },
      ],
    },
  ];
}

module.exports = { maintain, guildsWithin, remind };
